---
- name: Collecting Log Files of server1
  hosts: all
  become: yes
  tasks:
    - name: Making a directory for log collection
      file:
        path: /home/manage/logs/
        state: directory

    - name: Copying all log files of server1
      copy:
        src: /tmp/logs/syslog
        dest: /home/manage/logs

